name: wander
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  dart_openai: ^5.1.0
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.14
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_location_marker: ^8.0.8
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  latlong2: ^0.9.1
  path_provider: ^2.1.3
  record: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
